/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Test.H
**     Project   : BalanceCar
**     Processor : MCF52255CAF80
**     Beantype  : BitIO
**     Version   : Bean 02.073, Driver 01.01, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2014-11-23, 15:41
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       76            |  FEC_COL_PTI0
**             ----------------------------------------------------
**
**         Port name                   : PORTTI
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : 0x0001
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : up
**
**         Port data register          : PORTTI    [0x00100004]
**         Port control register       : DDRTI     [0x0010001C]
**         Port function register      : PTIPAR    [0x00100064]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool Test_GetVal(void);
**         ClrVal - void Test_ClrVal(void);
**         SetVal - void Test_SetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef Test_H_
#define Test_H_

/* MODULE Test. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Test_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define Test_GetVal() ( \
    (bool)((getReg8(PORTTI) & 0x01))   /* Return port output data */ \
  )

/*
** ===================================================================
**     Method      :  Test_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define Test_ClrVal() ( \
    (void)setReg8(CLRTI, 0xFE)         /* CLRTI0=0x00 */ \
  )

/*
** ===================================================================
**     Method      :  Test_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define Test_SetVal() ( \
    (void)setReg8(SETTI, 0x01)         /* SETTI0=0x01 */ \
  )



/* END Test. */
#endif /* #ifndef __Test_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
